# Generated by Django 5.0.4 on 2025-02-20 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_productrequest_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
