# Generated by Django 5.0.4 on 2025-02-20 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_alter_productrequest_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='requested_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
