# Generated by Django 5.0.4 on 2025-02-20 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_alter_productrequest_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery.status'),
        ),
    ]
