# Generated by Django 5.1.5 on 2025-02-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
