# Generated by Django 5.1.5 on 2025-02-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_booking_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
