# Generated by Django 5.1.5 on 2025-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0011_productrequest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='price_per_product',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
    ]
