# Generated by Django 5.1.5 on 2025-02-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0014_alter_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], default='Pending', max_length=50),
        ),
    ]
