# Generated by Django 5.1.5 on 2025-02-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0016_remove_booking_is_returned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrequest',
            old_name='product_name',
            new_name='account_name',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='account_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='bank_name',
            field=models.CharField(default='Default Bank', max_length=255),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='ifsc_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='product',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='grocery.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
