# Generated by Django 5.1.5 on 2025-02-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0017_rename_product_name_returnrequest_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='delivery_boy_images/')),
                ('idproof', models.FileField(upload_to='id_proofs/')),
            ],
        ),
    ]
