# Generated by Django 5.1.5 on 2025-02-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0019_deliveryboy_password_alter_deliveryboy_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='password',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
