# Generated by Django 5.1.5 on 2025-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0020_remove_deliveryboy_password_deliveryboy_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='password',
            field=models.CharField(default=1234, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
