# Generated by Django 5.1.5 on 2025-03-01 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0021_remove_deliveryboy_is_verified_deliveryboy_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.profile'),
        ),
    ]
