# Generated by Django 5.1.5 on 2025-03-01 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0022_deliveryboy_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery.deliveryboy'),
        ),
    ]
