# Generated by Django 5.1.5 on 2025-03-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0023_booking_delivery_boy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='grocery.profile'),
            preserve_default=False,
        ),
    ]
