# Generated by Django 5.1.6 on 2025-03-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0025_remove_notification_profile_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
