# Generated by Django 5.1.6 on 2025-03-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0026_booking_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='price_per_product',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
