# Generated by Django 5.1.6 on 2025-03-02 06:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0027_alter_productrequest_price_per_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price_per_product', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.supplierprofile')),
            ],
        ),
    ]
