# Generated by Django 5.1.6 on 2025-03-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0028_supplyhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplyHistory',
        ),
    ]
