# Generated by Django 5.1.6 on 2025-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0031_chat_file_alter_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Available', 'Available'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
