# Generated by Django 5.1.6 on 2025-03-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0033_alter_productrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Available', 'Available'), ('Not_Available', 'Not_Available')], default='Pending', max_length=20),
        ),
    ]
