# Generated by Django 5.1.6 on 2025-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0035_alter_productrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
