# Generated by Django 3.2.16 on 2025-03-04 17:07

from django.db import migrations
from django.utils import timezone

def fix_requested_at(apps, schema_editor):
    ProductRequest = apps.get_model('grocery', 'ProductRequest')
    for request in ProductRequest.objects.all():
        if not request.requested_at:
            request.requested_at = timezone.now()
            request.save()

class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0036_deliveryboy_is_approved'),
    ]

    operations = [
        migrations.RunPython(fix_requested_at),
    ]
