# Generated by Django 3.2.16 on 2025-03-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0037_auto_20250304_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='grocery.booking'),
        ),
    ]
